export interface DefaultQuestion {
  pergunta: string;
  tipo: number;
  alerta: number;
  labelPergunta?: string;
  labelAlerta?: string;
}

export interface DefaultAnamnesis {
  nome: string;
  questions: number[];
}

const QUESTIONS: DefaultQuestion[] = [
  { pergunta: "Queixa principal?", tipo: 3, alerta: 1 },
  { pergunta: "Sente alguma dor nos dentes ou na boca?", tipo: 2, alerta: 1, labelPergunta: "Onde dói? Intensidade? Frequência? Duração?" },
  { pergunta: "Está em tratamento médico?", tipo: 2, alerta: 1, labelPergunta: "Especifique:" },
  { pergunta: "Está usando medicação?", tipo: 2, alerta: 2, labelAlerta: "Toma", labelPergunta: "Qual(is)?" },
  { pergunta: "Possui alguma alergia? (Como penicilinas, AAS ou outra)", tipo: 2, alerta: 2, labelAlerta: "Alérgico a ", labelPergunta: "Especifique:" },
  { pergunta: "Já esteve internado?", tipo: 2, alerta: 1, labelPergunta: "Quando? Qual motivo?" },
  { pergunta: "Já teve hemorragia diagnosticada?", tipo: 1, alerta: 2, labelAlerta: "Risco de hemorragia" },
  { pergunta: "Possui alguma alteração sanguínea?", tipo: 2, alerta: 2, labelAlerta: "Alteração sanguínea", labelPergunta: "Qual?" },
  { pergunta: "Tem pressão alta?", tipo: 2, alerta: 2, labelAlerta: "Hipertenso", labelPergunta: "Controlada ou não controlada?" },
  { pergunta: "Possui diabetes?", tipo: 2, alerta: 2, labelAlerta: "Diabético", labelPergunta: "Tipo? Controlado ou não-controlado?" },
  { pergunta: "Possui asma?", tipo: 1, alerta: 2, labelAlerta: "Asmático" },
  { pergunta: "Possui anemia?", tipo: 1, alerta: 2, labelAlerta: "Anêmico" },
  { pergunta: "Possui alguma disfunção hepática?", tipo: 2, alerta: 2, labelAlerta: "Disfunção hepática", labelPergunta: "Qual?" },
  { pergunta: "Apresenta alguma disfunção renal?", tipo: 2, alerta: 2, labelAlerta: "Problema renal", labelPergunta: "Qual?" },
  { pergunta: "Possui alguma disfunção respiratória?", tipo: 2, alerta: 2, labelAlerta: "Problema respiratório", labelPergunta: "Qual?" },
  { pergunta: "Possui alguma alteração óssea?", tipo: 2, alerta: 2, labelAlerta: "Alteração óssea ", labelPergunta: "Qual?" },
  { pergunta: "Possui alguma doença transmissível? (HIV, Hepatite, outra)", tipo: 2, alerta: 2, labelAlerta: "Doença transmissível", labelPergunta: "Qual?" },
  { pergunta: "Possui câncer?", tipo: 2, alerta: 2, labelAlerta: "Câncer", labelPergunta: "Qual? Que tratamento foi utilizado?" },
  { pergunta: "Possui depressão?", tipo: 1, alerta: 1 },
  { pergunta: "Está ou esteve em tratamento psicológico?", tipo: 1, alerta: 1 },
  { pergunta: "Possui algum antecedente de febre reumática?", tipo: 1, alerta: 1 },
  { pergunta: "Possui algum antecedente de endocardite bacteriana?", tipo: 1, alerta: 2, labelAlerta: "Antecedente de endocardite bacteriana" },
  { pergunta: "Possui alguma outra doença/síndrome não mencionada?", tipo: 2, alerta: 2, labelPergunta: "Qual?" },
  { pergunta: "Já sofreu alguma reação alérgica ao receber anestesia?", tipo: 2, alerta: 2, labelAlerta: "Alérgico ao anestésico", labelPergunta: "Qual anestésico?" },
  { pergunta: "Escuta algum estalido ao abrir a boca?", tipo: 1, alerta: 1 },
  { pergunta: "Tem dificuldade de abrir a boca?", tipo: 1, alerta: 1 },
  { pergunta: "Sente dores no ouvido, cabeça, face, nuca ou pescoço?", tipo: 1, alerta: 1 },
  { pergunta: "Possui mau hálito?", tipo: 2, alerta: 1, labelPergunta: "Quando?" },
  { pergunta: "Possui azia, má digestão, refluxo, úlcera ou gastrite?", tipo: 1, alerta: 1 },
  { pergunta: "Apresenta sangramento a escovação?", tipo: 1, alerta: 1 },
  { pergunta: "Sente seus dentes moles?", tipo: 1, alerta: 1 },
  { pergunta: "Seus dentes são sensíveis a mudança de temperatura ou a alimentos doces?", tipo: 1, alerta: 1 },
  { pergunta: "Range os dentes?", tipo: 2, alerta: 1, labelPergunta: "Quando?" },
  { pergunta: "Já se submeteu à Cirurgia Oral (exodontia, freio labial, etc.)?", tipo: 2, alerta: 1, labelPergunta: "Quando? Sangrou muito?" },
  { pergunta: "Já se submeteu à Ortodontia (aparelhos e correção)?", tipo: 2, alerta: 1, labelPergunta: "Quando?" },
  { pergunta: "Já se submeteu à Periodontia (tratamento gengival)?", tipo: 2, alerta: 1, labelPergunta: "Quando?" },
  { pergunta: "Já se submeteu à Endodontia (tratamento de canal)?", tipo: 2, alerta: 1, labelPergunta: "Quando?" },
  { pergunta: "Já se submeteu à Profilaxia / Prevenção (limpeza, flúor, selante oclusal, etc.)?", tipo: 1, alerta: 1 },
  { pergunta: "Quando foi sua última vez que veio ao dentista? Como foi o atendimento?", tipo: 3, alerta: 1 },
  { pergunta: "Quantas vezes por dia escova os dentes?", tipo: 3, alerta: 1 },
  { pergunta: "Usa creme dental?", tipo: 1, alerta: 1 },
  { pergunta: "Usa fio dental?", tipo: 2, alerta: 1, labelPergunta: "Quantas vezes por semana?" },
  { pergunta: "Faz uso de antisséptico bucal?", tipo: 2, alerta: 1, labelPergunta: "Quantas vezes por dia?" },
  { pergunta: "Come muitos doces, balas entre outros?", tipo: 2, alerta: 1, labelPergunta: "Frequência?" },
  { pergunta: "Tem hábito de tomar café ou refrigerantes?", tipo: 2, alerta: 1, labelPergunta: "Frequência?" },
  { pergunta: "Ingere bebidas alcoólicas?", tipo: 2, alerta: 1, labelPergunta: "Frequência?" },
  { pergunta: "Fumante?", tipo: 2, alerta: 1, labelPergunta: "Há quanto tempo? Quantos cigarros por dia?" },
  { pergunta: "Usa drogas?", tipo: 2, alerta: 1, labelPergunta: "Qual(is)? Frequência de uso?" },
  { pergunta: "Tem o hábito de roer unha ou morder objetos (lápis, caneta, etc.)?", tipo: 1, alerta: 1 },
  { pergunta: "Está grávida?", tipo: 2, alerta: 2, labelAlerta: "Grávida", labelPergunta: "Quantos meses?" },
  { pergunta: "Está amamentando?", tipo: 1, alerta: 1 },
  { pergunta: "Toma anticoncepcional?", tipo: 2, alerta: 1, labelPergunta: "Qual" },
  { pergunta: "Qual a pressão arterial do paciente?", tipo: 3, alerta: 1 },
  { pergunta: "Qual frequência respiratória por minuto do paciente?", tipo: 3, alerta: 1 },
  { pergunta: "Qual a frequência cardíaca por minuto(bpm) do paciente?", tipo: 3, alerta: 1 },
  { pergunta: "O paciente possui alguma alteração ganglionar?", tipo: 2, alerta: 1, labelPergunta: "Em que região?" },
  { pergunta: "Apresenta alguma alteração de língua, lábio e/ou palato?", tipo: 2, alerta: 1, labelPergunta: "Onde? Qual?" },
  { pergunta: "Apresenta outra alteração na face não mencionada?", tipo: 2, alerta: 1, labelPergunta: "Onde? Qual?" },
  { pergunta: "Informações adicionais:", tipo: 3, alerta: 1 },
  { pergunta: "Você está com febre ou teve febre nos últimos 14 dias?", tipo: 1, alerta: 1 },
  { pergunta: "Você teve alguma experiência de início de problemas respiratórios, como tosse ou dificuldade de respirar nos últimos 14 dias?", tipo: 1, alerta: 1 },
  { pergunta: "Você teve algum tipo de contato com alguma pessoa confirmadamente infectada pelo 2019-nCoV nos últimos 14 dias?", tipo: 1, alerta: 1 },
  { pergunta: "Você teve contato com um grande número de pessoas diferentes no últimos 14 dias?", tipo: 1, alerta: 1 },
  { pergunta: "Você está usando máscara, álcool em gel ou outras medidas de biossegurança no seu dia a dia?", tipo: 1, alerta: 1 },
  { pergunta: "Possui alguma alteração cardiovascular?", tipo: 2, alerta: 2, labelAlerta: "Alteração cardíaca", labelPergunta: "Qual?" },
  { pergunta: "Realizou pré natal?", tipo: 1, alerta: 1 },
  { pergunta: "A criança nasceu com parto normal ou cesariana?", tipo: 3, alerta: 1 },
  { pergunta: "Peso ao nascer?", tipo: 3, alerta: 1 },
  { pergunta: "Realiza(ou) aleitamento materno?", tipo: 1, alerta: 1, labelPergunta: "Quanto tempo?" },
  { pergunta: "Realiza(ou) o uso de mamadeira ou chupeta?", tipo: 2, alerta: 1, labelPergunta: "A quanto tempo?" },
  { pergunta: "Realiza(ou) sucção de dedo ou lábio?", tipo: 2, alerta: 1, labelPergunta: "A quanto tempo?" },
  { pergunta: "Qual o perfil? (côncavo, convexo ou reto)", tipo: 3, alerta: 1 },
  { pergunta: "Qual a sobremordida? (aumentada, normal ou aberta)", tipo: 3, alerta: 1 },
  { pergunta: "Qual o trespasse horizontal? (aumentado, normal ou negativo)", tipo: 3, alerta: 1 },
  { pergunta: "Possui mordida cruzada?", tipo: 2, alerta: 1, labelPergunta: "Em que região? (anterior, posterior, unilateral ou bilateral)" },
  { pergunta: "Possui desvio de linha média?", tipo: 2, alerta: 1, labelPergunta: "Superior ou Inferior? Para qual lado?" },
  { pergunta: "O canino direito apresenta relação de: classe I, classe II, classe III ou topo?", tipo: 3, alerta: 1 },
  { pergunta: "O canino esquerdo apresenta relação de: classe I, classe II, classe III ou topo?", tipo: 3, alerta: 1 },
  { pergunta: "Qual a classe do paciente? (Classe I, II ou III)", tipo: 3, alerta: 1 },
  { pergunta: "Possui o hábito de tabagismo, alcoolismo ou uso de drogas?", tipo: 1, alerta: 1 },
  { pergunta: "Já se submeteu à Cirurgia?", tipo: 2, alerta: 1, labelPergunta: "Qual?" },
  { pergunta: "Realizou cirurgia bariátrica?", tipo: 2, alerta: 1, labelPergunta: "Há quanto tempo?" },
  { pergunta: "Tem muita exposição solar?", tipo: 2, alerta: 1, labelPergunta: "Qual periodicidade?" },
  { pergunta: "Apresenta manchas na pele?", tipo: 2, alerta: 1, labelPergunta: "Características?" },
  { pergunta: "Apresenta flacidez na pele?", tipo: 2, alerta: 1, labelPergunta: "Características?" },
  { pergunta: "Apresenta lesões de acne ativas?", tipo: 2, alerta: 1, labelPergunta: "Características?" },
  { pergunta: "Já realizou algum tratamento estético facial ou de pele?", tipo: 2, alerta: 1, labelPergunta: "Qual? Quando?" },
  { pergunta: "Já se submeteu a tratamentos com preenchedores não reabsorvíveis (PMMA)?", tipo: 1, alerta: 1 },
  { pergunta: "Fez uso de ácido ou algum peeling químico?", tipo: 2, alerta: 1, labelPergunta: "Qual?" },
  { pergunta: "Usa filtro solar regularmente?", tipo: 1, alerta: 1 },
  { pergunta: "Faz uso de produtos de cuidado diário da pele?", tipo: 2, alerta: 1, labelPergunta: "Quais?" },
  { pergunta: "O que você sente quando se olha no espelho?", tipo: 3, alerta: 1 },
  { pergunta: "O que você gostaria de melhorar no seu rosto?", tipo: 3, alerta: 1 },
  { pergunta: "Você prefere resultados mais rápidos e mais caros ou mais lentos e mais baratos?", tipo: 3, alerta: 1 },
];

const TEMPLATES: DefaultAnamnesis[] = [
  {
    nome: "Anamnese adulta",
    questions: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63],
  },
  {
    nome: "Anamnese HOF",
    questions: [0,1,2,3,4,6,7,8,9,10,11,12,13,14,16,17,19,22,23,25,45,46,49,50,51,57,58,64,80,81,82,83,84,85,86,87,88,89,90,91,92,93],
  },
  {
    nome: "Anamnese infantil",
    questions: [0,1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,25,26,27,28,29,31,32,33,34,35,36,37,38,39,40,41,42,43,44,48,65,66,67,68,69,70,52,53,54,55,56,57,58],
  },
  {
    nome: "Anamnese ortodôntica",
    questions: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,25,26,27,28,29,31,32,33,34,35,36,37,38,39,40,41,42,43,44,48,65,66,67,68,69,70,71,72,73,74,75,76,77,78,52,53,54,55,56,57,58],
  },
];

export { QUESTIONS, TEMPLATES };
